### ISSUE TITLE
Ruby module structure

### ISSUE THREAD

**Issue by razor-x** [seamapi/ruby-next#115]
- `Seam` is a module.
- `Seam.new` is an alias to `Seam::Http.new` and `Seam.from_*` are also aliased.
- `Seam::Http.new` is an alias to `Seam::Http::SingleWorkspace.new`
- `Seam::Webhook` is a class
- `Seam::Http` is a module
- `Seam::Http::SingleWorkspace` and `Seam::Http::MultiWorkspace` are classes.
- `Seam::Http::` contains the invalid option errors and api request / auth errors.
- `Seam::Resources` is a module with each resource, `Seam::Resources::Device` is a class.
- `Seam::Http::Routes` is a mixin module.
- `Seam::Http::WaitForActionAttempt`? Where to put the action attempt polling helper?
- Use https://github.com/lostisland/faraday?

**Comment by razor-x** [comment]
Why is `WorkspacesProxy` outside the Seam module?

**Comment by andrii-balitskyi** [comment]
Fixed in:
- https://github.com/seamapi/ruby-next/pull/89 
- https://github.com/seamapi/ruby-next/pull/96
- https://github.com/seamapi/ruby-next/pull/134
